<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\custumexport\CustumExport */
/* @var $form yii\widgets\ActiveForm */
$columns = [
    "order_id"=>Yii::t("app","order_id"),
    "created_at"=>Yii::t("app","created_at"),
    "user.name"=>Yii::t("app","Name"),
    "user.phone"=>Yii::t("app","Phone"),
    "delivery_date"=>Yii::t("app","delivery_date"),
    "country_id"=>Yii::t("app","country_id"),
    "region_id"=>Yii::t("app","region_id"),
    "address"=>Yii::t("app","address"),
    "status_id"=>Yii::t("app","status_id"),
    "amount_required"=>Yii::t("app","amount_required"),
    "attribute"=>Yii::t("app","attribute"),
    "attribute"=>Yii::t("app","attribute"),
    "order"=>Yii::t("app","order"),
    "note"=>Yii::t("app","note"),
    "delivery_price"=>Yii::t("app","delivery_price"),
    "delivery_price"=>Yii::t("app","delivery_price"),
    "discount"=>Yii::t("app","discount"),
    "area_id"=>Yii::t("app","area_id"),
    "company_delivery_id"=>Yii::t("app","company_delivery_id")];
?>


<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>


<div class="custum-export-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput() ?>

    <?= $form->field($model, 'columns')->textarea(['rows' => 6]) ?>
    <style>
        #modules {
            padding: 20px;
            background: #eee;
            margin-bottom: 20px;
            z-index: 1;
            border-radius: 10px;
        }

        #dropzone {
            padding: 20px;
            background: #eee;
            min-height: 100px;
            margin-bottom: 20px;
            z-index: 0;
            border-radius: 10px;
        }

        .active {
            outline: 1px solid red;
        }

        .hover {
            outline: 1px solid blue;
        }

        .drop-item {
            cursor: pointer;
            margin-bottom: 10px;
            background-color: rgb(255, 255, 255);
            padding: 5px 10px;
            border-radisu: 3px;
            border: 1px solid rgb(204, 204, 204);
            position: relative;
        }

        .drop-item .remove {
            position: absolute;
            top: 4px;
            right: 4px;
        }
    </style>
    <div class="container">
        <h1>Drag'n Drop Demo <small>jQuery UI and Bootstrap</small></h1>
        <form role="form">
            <details>
                <div class="form-group">
                    <input class="form-control" type="text" name="blah" placeholder="Additional details here" />
                </div>
            </details>
        </form>


        <div class="row">
            <div class="col-sm-6">
                <div id="modules">
                    <?php foreach ($columns as $column):?>
                        <p class="drag"><a class="btn btn-default"><?=$column[1]?></a></p>
                    <?php endforeach;?>>

                </div>
            </div>

            <div class="col-sm-6">
                <div id="dropzone"></div>
            </div>
        </div>
    </div>


    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

    <script>
        $('.drag').draggable({
            appendTo: 'body',
            helper: 'clone'
        });

        $('#dropzone').droppable({
            activeClass: 'active',
            hoverClass: 'hover',
            accept: ":not(.ui-sortable-helper)", // Reject clones generated by sortable
            drop: function (e, ui) {
                var $el = $('<div class="drop-item"><details><summary>' + ui.draggable.text() + '</summary><div><label>More Data</label><input type="text" /></div></details></div>');
                $el.append($('<button type="button" class="btn btn-default btn-xs remove"><span class="glyphicon glyphicon-trash"></span></button>').click(function () { $(this).parent().detach(); }));
                $(this).append($el);
            }
        }).sortable({
            items: '.drop-item',
            sort: function() {
                // gets added unintentionally by droppable interacting with sortable
                // using connectWithSortable fixes this, but doesn't allow you to customize active/hoverClass options
                $( this ).removeClass( "active" );
            }
        });
    </script>

</div>
